### PR TITLE
Add spectra matching functionality

### PR DESCRIPTION
**Pull request by jorainer**
Add `matchSpectra` and `MatchedSpectra` for MS2 spectra matching.

### CODE REVIEW

**Comment by jorainer** [comment]
Note: unit tests brake at present because of missing documentations in the *main* branch

**Review by michaelwitting — COMMENTED** [review]
Two things:
- Why is the tresholding done via an function?
- Type of mapping function in `CompareSpectraParam` goes via `...`? (e.g. "inner", "right")

**Comment by jorainer** [comment]
> - Why is the tresholding done via an function?

the idea was that this would enable the user to do some more fancy things like: report for each query spectrum the 10% of target spectra with the highest similarity or even try to use query-spectrum-specific cut-off, depending on e.g. the distribution of similarity scores against all target spectra.

> - Type of mapping function in CompareSpectraParam goes via ...? (e.g. "inner", "right")

Yep. All additional parameters for `joinPeaks` and `compareSpectra` can be passed *via* `...`. My idea was that we could have another param object(s) for the forward, reverse or the combined forward/reverse score. I would then implement them (they should extend the `CompareSpectraParam`) once I digged a little into the wrapper functions you're implemented.

**Comment by michaelwitting** [comment]
> > * Why is the tresholding done via an function?
> 
> the idea was that this would enable the user to do some more fancy things like: report for each query spectrum the 10% of target spectra with the highest similarity or even try to use query-spectrum-specific cut-off, depending on e.g. the distribution of similarity scores against all target spectra.
> 
> > * Type of mapping function in CompareSpectraParam goes via ...? (e.g. "inner", "right")
> 
> Yep. All additional parameters for `joinPeaks` and `compareSpectra` can be passed _via_ `...`. My idea was that we could have another param object(s) for the forward, reverse or the combined forward/reverse score. I would then implement them (they should extend the `CompareSpectraParam`) once I digged a little into the wrapper functions you're implemented.

Okay. Then everything is good for me. I guess we don't need the wrapper functions then. If we can supply "outer" and "right" via `...`

**Pull request merged**
